-- 1. 처음 푼거
SELECT a.NAME, a.COUNT
FROM (
         SELECT NAME, COUNT(NAME) AS COUNT
         FROM ANIMAL_INS
         GROUP BY NAME ) AS a
WHERE a.COUNT > 1

-- having 절을 사용한 정확한 답
SELECT NAME, COUNT(name) AS COUNT
FROM ANIMAL_INS
GROUP BY NAME
HAVING COUNT(NAME) > 1
ORDER BY NAME

